server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rucommercedb
    username: rucommerce
    password: ru1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
